"""
pages/2_Model_Insights.py
==========================
Transparency page: shows exactly how the deployed model performs — training
curves, confusion matrix, ROC/PR curves, and the full classification report,
all generated by src/evaluate.py.
"""

import sys
from pathlib import Path

import pandas as pd
import streamlit as st

sys.path.append(str(Path(__file__).resolve().parent.parent))

import config
from src import app_helpers as ui, utils

ui.page_setup("Model Insights", page_icon="📊")
ui.render_hero(
    "Model Insights",
    "Full transparency on how this model was trained and how it performs on held-out test data.",
    badge_text="Evaluation artifacts",
)

if not config.METRICS_PATH.exists():
    st.warning(
        "No evaluation artifacts found. Run `python -m src.evaluate` after training to generate "
        "metrics.json and the diagnostic plots this page displays.",
        icon="⚠️",
    )
    ui.render_footer()
    st.stop()

metrics = utils.load_json(config.METRICS_PATH)

# ------------------------------------------------------------------
# Headline metrics
# ------------------------------------------------------------------
c1, c2, c3, c4, c5 = st.columns(5)
c1.metric("Accuracy", f"{metrics['accuracy']*100:.2f}%")
c2.metric("ROC-AUC", f"{metrics['roc_auc']:.4f}")
c3.metric("Sensitivity (Recall)", f"{metrics['sensitivity_recall_positive']*100:.2f}%")
c4.metric("Specificity", f"{metrics['specificity']*100:.2f}%")
c5.metric("F1 (Pneumonia)", f"{metrics['f1_positive']:.4f}")

st.caption(
    f"Evaluated on {metrics['n_test']} held-out test images · Architecture: "
    f"**{metrics['architecture']}** · {metrics['total_params']:,} parameters · "
    f"Youden-optimal threshold: **{metrics['youden_optimal_threshold']:.3f}** "
    f"(default used: {metrics['default_threshold']:.2f})"
)

ui.render_divider()

# ------------------------------------------------------------------
# Training curves
# ------------------------------------------------------------------
st.markdown("### Training curves")
if config.TRAINING_CURVES_PATH.exists():
    st.image(str(config.TRAINING_CURVES_PATH), use_container_width=True)
else:
    st.info("Training curves not yet generated.")

ui.render_divider()

# ------------------------------------------------------------------
# Confusion matrix + ROC/PR
# ------------------------------------------------------------------
st.markdown("### Diagnostic plots")
col1, col2, col3 = st.columns(3)
with col1:
    if config.CONFUSION_MATRIX_PATH.exists():
        st.image(str(config.CONFUSION_MATRIX_PATH), use_container_width=True)
with col2:
    if config.ROC_CURVE_PATH.exists():
        st.image(str(config.ROC_CURVE_PATH), use_container_width=True)
with col3:
    if config.PR_CURVE_PATH.exists():
        st.image(str(config.PR_CURVE_PATH), use_container_width=True)

ui.render_divider()

# ------------------------------------------------------------------
# Classification report table
# ------------------------------------------------------------------
st.markdown("### Full classification report")
report = metrics["classification_report"]
rows = []
for key, val in report.items():
    if isinstance(val, dict):
        rows.append({
            "class": key,
            "precision": val.get("precision"),
            "recall": val.get("recall"),
            "f1-score": val.get("f1-score"),
            "support": val.get("support"),
        })
df = pd.DataFrame(rows).set_index("class")
st.dataframe(df.style.format({"precision": "{:.3f}", "recall": "{:.3f}", "f1-score": "{:.3f}"}),
             use_container_width=True)

ui.render_divider()

# ------------------------------------------------------------------
# Confusion matrix breakdown (plain language)
# ------------------------------------------------------------------
st.markdown("### What the confusion matrix means")
cm = metrics["confusion_matrix"]
tn, fp = cm[0]
fn, tp = cm[1]
cc1, cc2 = st.columns(2)
with cc1:
    ui.render_card(
        "Correct predictions",
        f"True Negatives (correctly identified NORMAL): <strong style='color:var(--text)'>{tn}</strong><br/>"
        f"True Positives (correctly identified PNEUMONIA): <strong style='color:var(--text)'>{tp}</strong>",
        icon="✅",
    )
with cc2:
    ui.render_card(
        "Errors",
        f"False Positives (NORMAL misread as PNEUMONIA): <strong style='color:var(--text)'>{fp}</strong><br/>"
        f"False Negatives (PNEUMONIA missed): <strong style='color:var(--text)'>{fn}</strong>",
        icon="⚠️",
    )

st.caption(
    "In a clinical screening context, **false negatives** (missed pneumonia) are typically the "
    "costlier error — this is why the sidebar threshold slider on the Diagnose page lets you trade "
    "specificity for sensitivity."
)

ui.render_footer()
